"use client";

import { useState, useEffect, useCallback } from "react";
import { supabase } from "@/lib/supabase";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Copy,
  Check,
  Search,
  Loader2,
  KeyRound,
  User,
  Calendar,
  Clock,
  Shield,
} from "lucide-react";

interface LicenceKey {
  id: string;
  key: string;
  type: string;
  status: string;
  assigned_to: string | null;
  assigned_email: string | null;
  expires_at: string | null;
  created_at: string;
}

export default function AdminLicencesPage() {
  const [keys, setKeys] = useState<LicenceKey[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [selectedKey, setSelectedKey] = useState<LicenceKey | null>(null);

  const loadKeys = useCallback(async () => {
    const { data } = await supabase
      .from("licence_keys")
      .select("*")
      .order("created_at", { ascending: false });
    setKeys(data ?? []);
    setLoading(false);
  }, []);

  useEffect(() => {
    loadKeys();
  }, [loadKeys]);

  const copyKey = (id: string, key: string) => {
    navigator.clipboard.writeText(key);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const filteredKeys = keys.filter(
    (k) =>
      k.key.toLowerCase().includes(search.toLowerCase()) ||
      (k.assigned_to || "").toLowerCase().includes(search.toLowerCase()) ||
      (k.assigned_email || "").toLowerCase().includes(search.toLowerCase())
  );

  const statusColor = (status: string) => {
    switch (status) {
      case "active": return "bg-green-100 text-green-700";
      case "inactive": return "bg-neutral-100 text-neutral-500";
      case "expired": return "bg-red-100 text-red-600";
      default: return "bg-neutral-100 text-neutral-500";
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-20">
        <Loader2 className="h-8 w-8 animate-spin text-neutral-400" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-neutral-900">Licence Keys</h1>
        <p className="mt-1 text-neutral-500">
          {keys.length} keys · Generated by Chariow after purchase
        </p>
      </div>

      {/* Search */}
      <div className="relative max-w-md">
        <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-neutral-400" />
        <Input
          placeholder="Search by key, name, or email..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="pl-9"
        />
      </div>

      {/* Keys table */}
      <Card>
        <CardContent className="p-0">
          {/* Header */}
          <div className="grid grid-cols-12 gap-4 border-b px-4 py-3 text-xs font-medium uppercase tracking-wider text-neutral-400">
            <div className="col-span-4">Licence Key</div>
            <div className="col-span-3">Customer</div>
            <div className="col-span-2">Status</div>
            <div className="col-span-2">Date</div>
            <div className="col-span-1"></div>
          </div>

          {/* Rows */}
          {filteredKeys.length === 0 ? (
            <p className="p-8 text-center text-neutral-500">
              {keys.length === 0 ? "No licence keys yet. Keys are generated when students purchase on Chariow." : "No results found"}
            </p>
          ) : (
            <div className="divide-y">
              {filteredKeys.map((lk) => (
                <div
                  key={lk.id}
                  className="grid grid-cols-12 gap-4 px-4 py-3 items-center hover:bg-neutral-50 cursor-pointer"
                  onClick={() => setSelectedKey(lk)}
                >
                  <div className="col-span-4 flex items-center gap-2">
                    <KeyRound className="h-3.5 w-3.5 text-neutral-300 shrink-0" />
                    <code className="text-xs font-mono text-neutral-700 truncate">
                      {lk.key}
                    </code>
                    <button
                      onClick={(e) => { e.stopPropagation(); copyKey(lk.id, lk.key); }}
                      className="shrink-0 text-neutral-300 hover:text-neutral-600"
                    >
                      {copiedId === lk.id ? (
                        <Check className="h-3.5 w-3.5 text-green-500" />
                      ) : (
                        <Copy className="h-3.5 w-3.5" />
                      )}
                    </button>
                  </div>
                  <div className="col-span-3">
                    <p className="text-sm text-neutral-900 truncate">
                      {lk.assigned_to || "—"}
                    </p>
                    <p className="text-xs text-neutral-400 truncate">
                      {lk.assigned_email || ""}
                    </p>
                  </div>
                  <div className="col-span-2">
                    <Badge variant="secondary" className={statusColor(lk.status)}>
                      {lk.status}
                    </Badge>
                  </div>
                  <div className="col-span-2 text-xs text-neutral-500">
                    {new Date(lk.created_at).toLocaleDateString()}
                  </div>
                  <div className="col-span-1 text-right text-xs text-neutral-400">
                    →
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Detail Modal */}
      <Dialog open={!!selectedKey} onOpenChange={() => setSelectedKey(null)}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <KeyRound className="h-5 w-5" />
              Licence Key Details
            </DialogTitle>
          </DialogHeader>

          {selectedKey && (
            <div className="space-y-4 mt-2">
              {/* Key */}
              <div className="rounded-lg bg-neutral-50 p-4 text-center">
                <p className="text-xs text-neutral-500 mb-1">Key</p>
                <code className="text-lg font-mono font-bold text-neutral-900">
                  {selectedKey.key}
                </code>
                <div className="mt-2">
                  <Button
                    variant="outline"
                    size="sm"
                    className="gap-1.5"
                    onClick={() => copyKey(selectedKey.id, selectedKey.key)}
                  >
                    {copiedId === selectedKey.id ? (
                      <><Check className="h-3.5 w-3.5 text-green-500" /> Copied</>
                    ) : (
                      <><Copy className="h-3.5 w-3.5" /> Copy</>
                    )}
                  </Button>
                </div>
              </div>

              {/* Details grid */}
              <div className="space-y-3">
                <div className="flex items-center gap-3">
                  <User className="h-4 w-4 text-neutral-400" />
                  <div className="flex-1">
                    <p className="text-xs text-neutral-500">Customer</p>
                    <p className="text-sm font-medium text-neutral-900">
                      {selectedKey.assigned_to || "Not assigned"}
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <span className="text-neutral-400 text-sm">@</span>
                  <div className="flex-1">
                    <p className="text-xs text-neutral-500">Email</p>
                    <p className="text-sm text-neutral-900">
                      {selectedKey.assigned_email || "—"}
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <Shield className="h-4 w-4 text-neutral-400" />
                  <div className="flex-1">
                    <p className="text-xs text-neutral-500">Status</p>
                    <Badge variant="secondary" className={statusColor(selectedKey.status)}>
                      {selectedKey.status}
                    </Badge>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <span className="text-neutral-400 text-sm">🏷</span>
                  <div className="flex-1">
                    <p className="text-xs text-neutral-500">Type</p>
                    <p className="text-sm text-neutral-900">{selectedKey.type}</p>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <Calendar className="h-4 w-4 text-neutral-400" />
                  <div className="flex-1">
                    <p className="text-xs text-neutral-500">Created</p>
                    <p className="text-sm text-neutral-900">
                      {new Date(selectedKey.created_at).toLocaleString()}
                    </p>
                  </div>
                </div>

                {selectedKey.expires_at && (
                  <div className="flex items-center gap-3">
                    <Clock className="h-4 w-4 text-neutral-400" />
                    <div className="flex-1">
                      <p className="text-xs text-neutral-500">Expires</p>
                      <p className="text-sm text-neutral-900">
                        {new Date(selectedKey.expires_at).toLocaleString()}
                      </p>
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
